### PR TITLE
Fix for PF2e 3.3

### LINKED ISSUE #14: Module not working with PF2e 3.3.0
When you click one of the buttons to roll, nothing shows in chat.
This error is from Intimidate: Demoralize
image

### PR DESCRIPTION
**Pull request by andriusch**
Fixes #14 
Looks like pf2e added a bunch more functions to ModifierPF2e and we need to add them. Luckily we can keep them empty as they don't need to do anything.

### CODE REVIEW

File: src/module/pf2e.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  adjustments: Record<string, unknown>[] = [];
+
+  constructor(data: Pick<ModifierPF2e, 'label' | 'modifier' | 'type'>) {
+    this.label = data.label;
+    this.modifier = data.modifier;
+    this.type = data.type;
+  }
+
+  update() {
+    return undefined;
```
Comment (andriusch) [inline src/module/pf2e.ts:14]: eslint complains if I leave functions empty.

File: src/module/sheet-skill-actions.ts [hunk 2]
```diff
@@ -46,7 +47,25 @@ Hooks.on('renderActorSheet', async (app: ActorSheet, html: JQuery<HTMLElement>)
   });
   const skillActionHtml = $(await renderTemplate(tpl, { skills: skillActions }));
 
-  skillActionHtml.on('click', '.item-image', (e) => {
+  skillActionHtml.on('click', '.skill-action.tag.variant-strike', function (e) {
```
Comment (jamespdaily) [inline src/module/sheet-skill-actions.ts:50]: Looks much better taking this out of the html template!
